services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    restart: unless-stopped
    ports:
      - "127.0.0.1:9191:9191"
    volumes:
      - /srv/docker/dispatcharr/config:/data

    
networks:
  default:
    name: proxy
    external: true
