services:
  caddy:
    build: .
    image: custom-caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/docker/caddy/data:/data
      - /srv/docker/caddy/config:/config

networks:
  default:
    name: proxy
    external: true

