services:
  caddy:
    build: .
    image: custom-caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/docker/caddy/data:/data
      - /srv/docker/caddy/config:/config

networks:
  default:
    name: proxy
    external: true

