x-common-env: &common-env
  PUID: 995
  PGID: 1001
  TZ: Europe/London

x-common: &common
  restart: unless-stopped

services:
  newt:
    image: fosrl/newt:latest
    container_name: newt-media
    restart: unless-stopped
    env_file: .env
    environment:
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jellyfin:
    <<: *common
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /srv/docker/jellyfin/web-config.json:/jellyfin/jellyfin-web/config.json
      - /srv/docker/jellyfin/config:/config
      - /srv/docker/jellyfin/cache:/cache
      - /mnt/drive/:/drive
    environment:
      JELLYFIN_PublishedServerUrl: https://play.beans.is
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  sabnzbd:
    <<: *common
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      <<: *common-env
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /mnt/drive/:/drive

  sonarr:
    <<: *common
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      <<: *common-env
    volumes:
      - /srv/docker/sonarr/config:/config
      - /mnt/drive/:/drive

  radarr:
    <<: *common
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      <<: *common-env
    volumes:
      - /srv/docker/radarr/config:/config
      - /mnt/drive/:/drive

  bazarr:
    <<: *common
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      <<: *common-env
    volumes:
      - /srv/docker/bazarr/config:/config
      - /mnt/drive/:/drive

  jfa-go:
    <<: *common
    image: hrfee/jfa-go
    container_name: jfa-go
    volumes:
      - /srv/docker/jellyfin/:/jf
      - /srv/docker/jfa-go/data:/data

  seerr:
    <<: *common
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      TZ: Europe/London
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    volumes:
      - /srv/docker/seerr/config:/app/config